Fixed bugs reported by early users
Prompt for image
Ignore no .network file
Present defaults if no .network file
Add local route
Deal with no compute hosts in cluster
Wait for VM or exit on VM create error
Wait for VM ping

diff --git a/create_vm b/create_vm
--- a/create_vm
+++ b/create_vm
@@ -2,11 +2,9 @@
 #
 # assumes that openstack credentails are set in this file
 source ~/openrc
-source .network
-#!/bin/bash
-# Our generic lab model is to create a network that uses the VLAN id to help
-# define Subnet IPs.  We'll do this here for both our "public" access network
-# and for the OpenStack L3 agent NATd network
+source .network >& /dev/null
+
+
 function sleep_count  () {
 # pass in a time (usually in seconds) and a message ( in "")
 echo -n $2
@@ -17,41 +15,12 @@ echo -n $2
     sleep 1
     (( count ++ ))
   done
-  echo "done"
 }
+COMPUTE_HOST=`nova-manage host list | grep com | head -1 | awk -F' ' '{print $1}'`
+if [ -z ${COMPUTE_HOST} ] ; then
+ die "There don't seem to be any 'compute' hosts available, perhaps run puppet agent on them again?"
+fi
    
-# otherwise, use an Ubuntu precise image. This is a larger image, but a little more
-# feature-full and realistic
-IMAGE_ID=`glance index | grep 'precise-amd64' | head -1 |  awk -F' ' '{print $1}'`
-if [ -z ${IMAGE_ID} ]; then
-  wget http://128.107.252.163/precise.img
-  # import that image into glance
-  glance image-create --name="precise-amd64" --is-public=true --container-format=ovf --disk-format=qcow2 < precise.img
-  # Caputre the Image ID so taht we can call the right UUID for this image
-  IMAGE_ID=`glance index | grep 'precise-amd64' | head -1 |  awk -F' ' '{print $1}'`
-fi
-login_user='ubuntu'
-
-# create a pub/priv keypair
-if ! [ -e /tmp/id_rsa ] ; then
-  ssh-keygen -f /tmp/id_rsa -t rsa -N ''
-  
-  #add the public key to nova.
-  nova keypair-add --pub_key /tmp/id_rsa.pub key_percise
-fi
-
-# create a security group so that we can allow ssh, http, and ping traffic
-# when we add a floating IP (assuming you are adding floating IPs)
-SEC_GROUP=`nova secgroup-list | grep nova_test`
-if [ -z "${SEC_GROUP}" ] ; then
-nova secgroup-create nova_test 'Precise test security group'
-nova secgroup-add-rule nova_test tcp 22 22 0.0.0.0/0
-nova secgroup-add-rule nova_test tcp 80 80 0.0.0.0/0
-nova secgroup-add-rule nova_test icmp -1 -1 0.0.0.0/0
-fi
-# request a floating IP address, and extract the address from the results message
-# floating_ip=`nova floating-ip-create | grep None | awk '{print $2}'`
-
 # initialize a network in quantum for use by VMs and assign it a non-routed subnet
 NET_ID=`quantum net-list | grep private | awk -F' ' '{ print $2 }'`
 
@@ -59,32 +28,61 @@ if [ -z ${NET_ID} ] ; then
   ./net_setup
   NET_ID=`quantum net-list | grep private | awk -F' ' '{ print $2 }'`
 fi
-instance_name='precise_test_vm'
+
+IMAGE_ID=`glance index | grep 'test' | head -1 |  awk -F' ' '{print $1}'`
+if [ -z ${IMAGE_ID} ]; then
+  [ -z ${IMAGE_LOC} ] && IMAGE_LOC='http://cloud-images.ubuntu.com/precise/current/precise-server-cloudimg-amd64-disk1.img'
+  # IMAGE_LOC='http://128.107.252.163/precise.img'
+  read -p "Where would you like to download a QCOW format test image from [${IMAGE_LOC}]: " IMAGE_LOC
+  echo "export IMAGE_LOC=${IMAGE_LOC}" >> .network
+  wget -O /tmp/test.img ${IMAGE_LOC} 
+  # import that image into glance
+  glance image-create --name="test" --is-public=true --container-format=ovf --disk-format=qcow2 < /tmp/test.img
+  # Caputre the Image ID so taht we can call the right UUID for this image
+  IMAGE_ID=`glance index | grep 'test' | head -1 |  awk -F' ' '{print $1}'`
+fi
+
+# create a pub/priv keypair
+if ! [ -e /tmp/id_rsa ] ; then
+  ssh-keygen -f /tmp/id_rsa -t rsa -N ''
+  
+  #add the public key to nova.
+  nova keypair-add --pub_key /tmp/id_rsa.pub key_test
+fi
+
+# create a security group so that we can allow ssh, http, and ping traffic
+# when we add a floating IP (assuming you are adding floating IPs)
+SEC_GROUP=`nova secgroup-list | grep sec_test`
+if [ -z "${SEC_GROUP}" ] ; then
+nova secgroup-create sec_test 'Test security group'
+nova secgroup-add-rule sec_test tcp 22 22 0.0.0.0/0
+nova secgroup-add-rule sec_test tcp 80 80 0.0.0.0/0
+nova secgroup-add-rule sec_test icmp -1 -1 0.0.0.0/0
+fi
+
+instance_name='test_vm'
 # Boot the added image against the "1" flavor which by default maps to a micro instance.   Include the percise_test group so our address will work when we add it later 
 NOVA_EXIST=`nova list | grep ${instance_name}`
 if ! [ "${NOVA_EXIST}" ] ; then
-  nova boot --flavor 1 --security_groups nova_test --nic net-id=${NET_ID} --image ${IMAGE_ID} --key_name key_percise $instance_name
+  BUILD_STAT=`nova boot --flavor 1 --security_groups sec_test --nic net-id=${NET_ID} --image ${IMAGE_ID} --key_name key_test $instance_name | grep status | awk -F' ' '{print $4}'`
 else
  exit 1
 fi
 
-# let the system catch up
-sleep_count 15 "Sleeping for 15 seconds to allow the system to catch up"
+echo "Waiting for VM to boot"
+while [ "${BUILD_STAT}" != "ACTIVE" ]; do
+ BUILD_STAT=`nova show test_vm | grep status | awk -F' ' '{print $4}'`
+ sleep_count 5 " . "
+ if [ "${BUILD_STAT}" == 'ACTIVE' ]; then
+   break
+ elif [ "${BUILD_STAT}" == 'ERROR' ]; then
+   die "The vm failed to build." 
+ fi
+done
 
 # Show the state of the system we just requested.
 PRIV_IP=`nova show $instance_name | grep 'private network' | awk -F' ' '{print $5}'`
-echo PRIVATE IP: ${PRIV_IP}
-
-## wait for the server to boot
-#sleep 15
-
-### Now add the floating IP we reserved earlier to the machine.
-#nova add-floating-ip $instance_name $floating_ip
-## Wait  and then try to SSH to the node, leveraging the private key
-## we generated earlier.
-#sleep 15
-#ssh $login_user@$floating_ip -i /tmp/id_rsa
-#
+echo -e "\nPRIVATE IP: ${PRIV_IP}"
 
 PUB_NET_ID=`quantum net-list | grep ' public ' | awk -F' ' '{print $2}'`
 PRIV_ROUTER=`quantum router-list | grep private_router_1 | awk -F' ' '{print $2}'`
@@ -95,18 +93,21 @@ VM_PORT_ID=`quantum port-list | grep "${PRIV_IP}" | awk -F' ' '{print $2}'`
 FLOAT_ID=`quantum floatingip-create ${PUB_NET_ID} | grep ' id ' | awk -F' ' '{print $4}'`
 
 FLOAT_IP=`quantum floatingip-list | grep ${FLOAT_ID} | awk -F' ' '{print $5}'`
-if [ ${FLOAT_IP} == '|' ] ; then
-  sleep_count 10 "Waiting for the IP to be associated and quantum to catch up..."
-  FLOAT_IP=`quantum floatingip-list | grep ${FLOAT_ID} | awk -F' ' '{print $6}'`
-fi
+#if [ ${FLOAT_IP} == '|' ] ; then
+#  sleep_count 20 "Waiting for the IP to be associated and quantum to catch up..."
+#  FLOAT_IP=`quantum floatingip-list | grep ${FLOAT_ID} | awk -F' ' '{print $6}'`
+#fi
 echo "Floating IP: ${FLOAT_IP}"
 quantum floatingip-associate ${FLOAT_ID} ${VM_PORT_ID}
 # Let's see if we can hit our node
 ip netns exec qrouter-${PRIV_ROUTER} ip addr list
-sleep_count 10 "Waiting for the IP to be associated and quantum to catch up..."
-echo pinging inside host: ip netns exec qrouter-${PRIV_ROUTER} ping -c 3 ${FLOAT_IP}
-if ! ip netns exec qrouter-${PRIV_ROUTER} ping -c 3 ${FLOAT_IP} ;then
- echo '!!!! Cant ping the host!!!'
- echo 'Exiting. Fix your network, then try again'
- exit 1
+echo -e "\n\npinging inside host: ip netns exec qrouter-${PRIV_ROUTER} ping -c 1 ${FLOAT_IP}\n\n"
+RETRY=0
+while [ "${RETRY}" -le "5" ] ; do
+(( RETRY ++ ))
+sleep_count 5 "Waiting for the IP to be associated and quantum to catch up..."
+if ip netns exec qrouter-${PRIV_ROUTER} ping -c 1 ${FLOAT_IP} ;then
+ echo -e "\n\nSuccess!\n\n"
+ exit 0
 fi
+done
diff --git a/reset b/reset
--- a/reset
+++ b/reset
@@ -1,15 +1,8 @@
 #!/bin/bash
 source ~/openrc
-# Our generic lab model is to create a network that uses the VLAN id to help
-# define Subnet IPs.  We'll do this here for both our "public" access network
-# and for the OpenStack L3 agent NATd network
+source .network >& /dev/null
 
-#if ! `quantum port-delete -- private_router_1 --device_owner network:router_gateway`; then
-# echo 'cloud not delete router gateway port'
-# exit 1
-#fi
-
-if ! nova delete precise_test_vm ; then
+if ! nova delete test_vm ; then
  echo perhaps you did not create a vm?
  echo continuing...
 fi
@@ -20,33 +13,27 @@ FLOAT_ID=`quantum floatingip-list | grep 192 | awk -F' ' '{print $2}'`
   echo perhaps you did not create a floating ip?
   echo continuing...
  fi
-#if ! quantum router-interface-delete private_router_1 "${PRIV_SUBNET_ID}" ;then
-# echo 'could not delete router port'
-# exit 1
-#fi
 
 if ! quantum router-gateway-clear private_router_1 ; then
  echo 'could not clear router gateway'
-# exit 1
 fi
 
 if ! quantum net-delete public  ; then
  echo 'public net not deleted'
-# exit 1
 fi
 if ! quantum net-delete private ; then
  echo 'private net not delted'
-# exit 1
 fi
 
 if ! quantum router-delete private_router_1 ; then
  echo 'router not delted'
-# exit 1
+fi
+if ! [ -z ${PRIV_IP} ] && route del -net ${PRIV_IP}/${PRIV_CIDR} ; then
+  echo 'metadata route not found'
 fi
 
 if ! quantum-netns-cleanup ; then
  echo 'quantum-netns-cleanup failed!'
-# exit 1
 fi
 exit 0
 
